### ISSUE TITLE
'Unsupported document type:' error on startup and cannot save a file

### ISSUE THREAD

**Issue by robcsi** [evolus/pencil#662]
* Operating system: Arch linux
* Pencil version: 3.1.0.6

I get the mentioned error on startup, with no other info. Also, I doesn't save any file anywhere with no error or message, not even when starting from command line to see.

**Comment by rhein** [comment]
Same problem for me, also on Arch Linux. 

If started from terminal I see 2 error messages (or rather warnings):
directly at start: `ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.`
when trying to save a document: `DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

Possibly the arch package is just outdated.

**Comment by robcsi** [comment]
Right, I see now that I get the same messages .

**Comment by fh-cy** [comment]
i am also on arch, i figured out that in developmnet branch this is already fixed: https://github.com/evolus/pencil/commit/a98fa2831daa9f1ff3f212ef36ace36fd3a69d4b

use `aur/evolus-pencil-devel-git` or downgrade (not tested) electron to version 9.* or delete electron and use only electron9 package

**Comment by cinatic** [comment]
i am also on arch, i figured out that in developmnet branch this is already fixed: https://github.com/evolus/pencil/commit/a98fa2831daa9f1ff3f212ef36ace36fd3a69d4b

use `aur/evolus-pencil-devel-git` or downgrade (not tested) electron to version 9.* or delete electron and use only electron9 package

**Comment by robcsi** [comment]
Thanks for the tip, I installed that package.

I still get the error message at startup, but I can save files now.

**Comment by sickcodes** [comment]
Same issue, will post in the AUR 


https://github.com/evolus/pencil/issues/661
